### ISSUE TITLE
Bump version in child objects.

### ISSUE THREAD

**Issue by ajbogh** [stevelacy/gulp-bump#30]
I have a version.txt file that is currently being bumped by grunt-bump. The contents of the file are below:

    {
        versionInfo: {
            version: 0.0.1
        }
    }

Can the "key" parameter be dot separated so that any key in the structure can be bumped, without affecting the overall structure?

The workaround that I've developed is here, but it's a synchronous task in an asynchronous process so it also requires Q:

    gulp.task('bump', function(){
        var version = null;
        var deferred = Q.defer();
        gulp.src(['package.json', 'bower.json'])
            .pipe(bump())
            .pipe(tap(function(file){
                if(version){ return; }
                var json = JSON.parse(String(file.contents));
                version = json.version;
            }))
            .pipe(gulp.dest('./test'))
            .on('end', function(){
                gulp.src(['version.txt'])
                    .pipe(jeditor(function(json){
                        json.versionInfo.version = version;
                        return json;
                    }))
                    .pipe(gulp.dest('./'))
                    .pipe(function(){
                        deferred.resolve();
                    });
            });
        return deferred.promise;
    });

**Comment by stevelacy** [comment]
This plugin was designed for bumping npm and similar package file structures by looking for the toplevel version key thus the toplevel `version` key

Do you want to create a PR for it?

**Comment by stevelacy** [comment]
Added with 2d99aabe8b71ac252909467a93d7c53fe9fe4b44

**Comment by stevelacy** [comment]
published to `0.2.0`

**Comment by ajbogh** [comment]
Thanks!
