### ISSUE TITLE
Bump version x.x.10 is .1

### ISSUE THREAD

**Issue by lukasoppermann** [stevelacy/gulp-bump#34]
Just noticed, that a version with a patch .10 is reduce to .1 thus overwriting the original .1 tag

Is this typical semversion or a bug?

**Comment by stevelacy** [comment]
That does seem to be a bug, are you patching from 0.0.9?

**Comment by stevelacy** [comment]
I updated semver and modified the test to check for that particular patch (0.0.9 - 0.0.10)

**Comment by lukasoppermann** [comment]
Awesome, i was patching Form 0.1.9 on.

**Comment by stevelacy** [comment]
I also added features and published to v`0.2.0` / v`0.2.1`
