### ISSUE TITLE
Add support for the rest of the pre_ bump types node-semver supports

### ISSUE THREAD

**Issue by adam-lynch** [stevelacy/gulp-bump#38]
i.e. premajor, minor, preminor and prepatch.

Unless there's a reason why it's not there :smile:

**Comment by stevelacy** [comment]
Where are the docs for it?

**Comment by adam-lynch** [comment]
See the `inc` section at https://github.com/npm/node-semver#functions

**Comment by stevelacy** [comment]
That is supported: https://github.com/stevelacy/gulp-bump/blob/master/index.js#L41

**Comment by adam-lynch** [comment]
Great, I guess it just needs to be added to the readme so.


Regards,
Adam Lynch

**Comment by noknokcody** [comment]
Love this package to the moon and back but if this was added to documentation it would've saved me a fair bit of time 👍

**Comment by stephenlacy** [comment]
@noknokcody PR?

**Comment by noknokcody** [comment]
Apologies for the cross-post (and my ignorance). Done 👍 
https://github.com/stevelacy/bump-regex/pull/27
