### ISSUE TITLE
Incorrect work with nested keys

### ISSUE THREAD

**Issue by diolive** [stevelacy/gulp-bump#42]
When I use dotted key (e.g. 'AppSettings.Version') the script can't read actual version from json because `content[opts.key]` works wrong with nested properties.
It affects in some places:
* when I set version explicitly it's writing to dotted property instead of nested one:
```
{
   AppSettings: {
      Version: "0.1.0"
   }, 
   ...
   "AppSettings.Version": "0.1.1"
}
```
* when it checking with semver it's **always** invalid because of `undefined`

It's need to replace plain `content[opts.key]` to something more intellectual like `Object.byString` from [this example](http://jsfiddle.net/alnitak/hEsys/).

**Comment by stevelacy** [comment]
https://github.com/stevelacy/gulp-bump/blob/master/test/dotNotation.js

The test confirms that the nested object does work.

Unless you are referring to something else.

**Comment by diomercury** [comment]
The test using dotted access to nested object that works fine (hardcoded `json.subversion.version`).
The package using string-based syntax that doesn't work (e.g. `json['subversion.version']`)
