### ISSUE TITLE
Nested properties don't work with version property

### ISSUE THREAD

**Issue by CrankNPlank** [stevelacy/gulp-bump#43]
Hello,

Great plugin! Thanks for your work on it.

I've run into an issue when using nested properties via dot notation. We develop in-house NPM packages that are included via devDependencies in **package.json**. When ready to issue a PR, and then subsequently send to QA, we want to bump the version for any NPM packages we worked on with the change, and then update the referenced version in the main application's **package.json** file.

In the below example, I already have access to the dependent package's new version number and am trying to apply it to the app's reference in the **devDependencies** section of **package.json**:

**package.json**
```json
{
  "name": "my-app",
  "version": "0.1.0",
  ...,
  "devDependencies": {
    ...,
    "my-custom-package": "1.0.1",
    ...
  }
}
```

**gulp task**
```javascript
gulp.task('bumpAppVersionTest', function () {

  var pkgLoc = 'devDependencies.my-custom-package';
  var pkgVer = '1.0.2';

  return gulp.src('./package.json')
    .pipe(bump({key: pkgLoc, version: pkgVer}))
    .pipe(gulp.dest('./'));

});
```

When the task is run, the following is the result:

**Console output**
```console
...
[09:09:56] Creating key devDependencies.my-custom-package with version: 1.0.2
[09:09:56] Bumped 'package.json' devDependencies.my-custom-package to: 1.0.2
...
```

This results in a new key being added at the root level to **package.json**:

**package.json - after the task has run**
```json
{
  "name": "my-app",
  "version": "0.1.0",
  ...,
  "devDependencies": {
    ...,
    "my-custom-package": "1.0.1",
    ...
  },
  ...,
  "devDependencies.my-custom-package": "1.0.2"
}
```

If I modify the task to not include the version property the nesting works as expected:

**gulp task**
```javascript
gulp.task('bumpAppVersionTest', function () {

  var pkgLoc = 'devDependencies.my-custom-package';
  var pkgVer = '1.0.2';

  return gulp.src('./package.json')
    .pipe(bump({key: pkgLoc}))
    .pipe(gulp.dest('./'));

});
```

**Console output**
```console
[09:15:22] Bumped 'package.json' devDependencies.my-custom-package to: 1.0.2
```

**package.json - after the task has run**
```json
{
  "name": "my-app",
  "version": "0.1.0",
  ...,
  "devDependencies": {
    ...,
    "my-custom-package": "1.0.2",
    ...
  }
}
```

Seems that the inclusion of the version property is fouling things up. I didn't test adding other properties, just version.

**Comment by stevelacy** [comment]
Nice find, I'll look into it

**Comment by CrankNPlank** [comment]
@stevelacy Great! Thanks, and let me know if I can help.

**Comment by stevelacy** [comment]
Fixed

**Comment by CrankNPlank** [comment]
@stevelacy Thank you for the quick turnaround. You rock! Only one thing to point out...

Everything functions as expected now...the correct existing package is found and updated to the given version, however the console message is still stating it's creating the key:

```console
[12:57:21] Creating key devDependencies.my-custom-package with version: 2.1.0
```

Regardless, it works! Bravo, and thanks again!

**Comment by stevelacy** [comment]
Yes, I noticed that.
This line checks to see if the original json has the version: https://github.com/stevelacy/gulp-bump/blob/master/index.js#L55
I'll probably fix it in a bit
