### ISSUE TITLE
Feature Request(s): Tag version and create HISTORY.md

### ISSUE THREAD

**Issue by saponifi3d** [stevelacy/gulp-bump#46]
1. It'd be awesome if there was a boolean flag for creating a git tag with the current version too. That way you could have a git tag created for every version bump you do too.

2. Use the history and top level commits messages to build out a HISTORY.md or some sort of change log that is auto generated.  I'd probably just use it as a starting point to write my own change log, but with open source dev most of the things that are merged to master tend to be either feature branches or bug fixes.  Having a list of the merges auto created would be amazing!

Granted, these are both pretty specific to git, but i think you could do either of them with mercurial or svn too, but I think most people are using github to host their open source projects.

**Comment by stevelacy** [comment]
[gulp-git](npm.im/gulp-git) :smile: 

Keeping the two separate insures that the plugins follow the gulp plugin guidelines (plugin must do one thing, not the kitchen sink).

There also is this: https://github.com/stevemao/gulp-conventional-changelog
Haven't used it yet

**Comment by saponifi3d** [comment]
nice!!! i didn't know about that. thanks!

**Comment by stevelacy** [comment]
:+1: 
Cheers
