### ISSUE TITLE
bump works on package.json but git doesn't see the change!

### ISSUE THREAD

**Issue by ksnyde** [stevelacy/gulp-bump#47]
I have a task called `bump-npm`:

```
gulp.task('bump-npm', function() {
  return gulp.src('./package.json')
    .pipe(bump())
    .pipe(gulp.dest('./'));
});
```

it works in so far as it bumps the version from 0.0.x to 0.0.x+1. Unfortunately it must be doing it in some sort of "sneaky" way as my git status remains unchanged even though the package (not surprisingly is NOT in `.gitignore`).

Here's a video demonstrating this:

> [video link](https://vimeo.com/147616660)

I suspect it may be down to bump-npm not modifying the file's date.

**Comment by stevelacy** [comment]
Excellent video, thank you.
What filesystem are you using?
I notice the `Volumes` folder, is it a separate drive which might have a different user, though you have write access?

This seems related, rather recent as well: https://github.com/gulpjs/gulp/issues/1414

**Comment by ksnyde** [comment]
I'm on OSX and the Volume you refer to is a permanent RAID array which I use for all of my development work. Nothing is definitive but I think permissioning and ownership is probably not the issue. 

WRT to the issue you pointed to ... I have a stronger affinity to that. I must admit I've only started using Gulp in the past week and Gulp 4.0 in the past few days. I guess if the final pipe to `gulp.dest('./')` is the function actually responsible for dropping the file on the filesystem then it would make sense that it is the responsible party. 

For the time being I have solved my own problem by adding a quick shell out to the command line where I'm just touching the file to get it's change recognized. Works but avoids the real solution. :)

**Comment by stevelacy** [comment]
It's pretty bad that you need to add that shell command...
Does any other gulp task with `gulp.dest` cause file changes?

**Comment by ksnyde** [comment]
As this is a backend micro-service rather than anything needing standard frontend tooling (e.g., uglify, concatination, SASS transpiling, etc.). Although on further inspection I see that the one useful test is in my Babel transpile. Let me see if I get the same result. Back in a moment.

**Comment by ksnyde** [comment]
Oh, just realised that this test doesn't work because the 'clean' clears out the directory so of course the filesystem's date is seen as new. :(

**Comment by ksnyde** [comment]
Ignore that last ramble, easy to get around that. I have found that in _both_ cases the filesystem's date is left unchanged. Interesting. I guess maybe this issue can be closed but this is definitely a big issue for gulp 4. Hope it gets fixed soon.

**Comment by phated** [comment]
@ksnyde thanks for linking back to the vinyl-fs issue.  This is actually a huge issue that we are trying to solve and then gulp 4 should be ready for primetime.  It's a pretty complex issue but I hope we are able to wrap it up soon.

**Comment by ksnyde** [comment]
@phated best of luck ... loving the other aspects of Gulp 4

**Comment by stefanwalther** [comment]
Temporary workaround: Use `gulp-touch`and add

```js
...
.pipe( plugins.touch() )
```

at the end.

**Comment by stevelacy** [comment]
This is fixed, right? @phated

**Comment by phated** [comment]
@stevelacy I don't think this is fixed, but it's not gulp-bump's issue either way.

**Comment by AlecRust** [comment]
Is there a gulp 4 issue we can follow for this?
