### ISSUE TITLE
How to get to 1.1.0-RC1 from 1.0.3

### ISSUE THREAD

**Issue by KrunchMuffin** [stevelacy/gulp-bump#48]
I can't figure out how to get there from here. If I do bump minor i get my 1.1.0, then if i do bump prerelease I get 1.1.1-RC1.

**Comment by stevelacy** [comment]
All supported version are semver: http://semver.org/
I do not know of a way to bump a prerelease to a minor, only patch.

**Comment by astral-sa** [comment]
`options.type` in the readme should probably be updated to reflect that `preminor` and `premajor` are valid `type` values.

@KrunchMuffin You're looking for `preminor`.

**Comment by stevelacy** [comment]
@astral-sa do you know where are the official docs for that?
Closest I found: https://github.com/npm/node-semver#functions

**Comment by astral-sa** [comment]
I think that's about as good as it gets as far as official docs for node's `semver.inc` function. Good catch though; it looks like I missed noting `prepatch` in my earlier comment. :smile:
