### ISSUE TITLE
Inconsistent bumping with Gulp 4

### ISSUE THREAD

**Issue by hoodsy** [stevelacy/gulp-bump#49]
Using the hello world example from the docs, my ```bower.json``` updates inconsistently. I always receive the output that the bump was successful, but frequently my ```bower.json``` file isn't updated.

I'm using Gulp 4 - maybe my issues are related to the new version?

```javascript
return gulp.src('./bower.json')
    .pipe(bump( { type: bumpType } ))
    .pipe(gulp.dest(config.package.dest))
```

**Comment by stevelacy** [comment]
gulp 3/4 only changed task orchestration. Can you create an example repo to reproduce the issue?

**Comment by stevelacy** [comment]
is it related to #47?

**Comment by stevelacy** [comment]
closing as its #47
