### ISSUE TITLE
v2 is breaking, gutil.log is missing at the end

### ISSUE THREAD

**Issue by binarykitchen** [stevelacy/gulp-bump#51]
I've got a similar script like this one https://github.com/nicksrandall/gulp-release-tasks/blob/master/tasks/release.js which relies on the output of `gulp-bump` to figure out the next version. With your latest version v2 this is breaking.

Can you put back the gutil.log like this one?
https://github.com/stevelacy/gulp-bump/blob/4385850bb490c358f5bc3b16fe99c476c48ddd59/index.js#L87

Thanks!

**Comment by stevelacy** [comment]
Yes

**Comment by stevelacy** [comment]
Logs added to master. Returning the entire bump object as well with new/prev version and type.

**Comment by binarykitchen** [comment]
awesome dude, thx, will check out soon and close when verified

**Comment by binarykitchen** [comment]
@stevelacy can you npm publish that new version pls?

**Comment by stevelacy** [comment]
Yes, I was waiting for your response before publishing

**Comment by binarykitchen** [comment]
thanks, works well now!
