### ISSUE TITLE
operation not permitted,

### ISSUE THREAD

**Issue by Kratos-SA** [stevelacy/gulp-bump#52]
Error: EPERM: operation not permitted, I am getting this error after I run bump even though the package.json file has full access [09:54:21] Bumped 3.2.13 to 3.2.14 with type: patch and the package.json file is updating.

**Comment by stevelacy** [comment]
I assume this is windows?
https://github.com/npm/npm/issues/10826
https://github.com/npm/npm/issues/10826#issuecomment-203438132
