### ISSUE TITLE
Bump is stripping out build info from tag

### ISSUE THREAD

**Issue by jdrew1303** [stevelacy/gulp-bump#54]
Hey,

[Semver describes the ability to add addition of prerelease and build metadata at the end of a version string](http://semver.org/#spec-item-10). Currently if I pass `1.0.6-1+build-623` to the version option it will only output `1.0.6-1`.  

Im hoping to use this to output to a [constants file for a angular app](https://github.com/guzart/gulp-ng-constant), allowing me to log errors against a build version in the running app with [Sentry](https://getsentry.com/welcome/). We deploy new builds without updating the version for refactors of the code. We only use patch for bugs. 

Not sure if its would help with the internals of gulp bump but Im using [semver-utils](https://github.com/coolaj86/semver-utils) to parse the string and increment before passing it to bump.

Thanks for the great lib. Currently using it for tagging builds and its working great. 👍

**Comment by stevelacy** [comment]
You need to specify the version type as pre release and add the preid as the metadata

```js
{
  type: 'prerelease',
  preid: '1+build-' + metaData
}
```

**Comment by jdrew1303** [comment]
Ah ok. Will this also mean that the build metadata will be reset when I do anything other than  a prerelease bump?

**Comment by stevelacy** [comment]
Yes as it is creating a new version with the type set to minor, major, etc

**Comment by jdrew1303** [comment]
Ok, Ill prob have to manually handle updating the strings to keep the build version between versions. :disappointed:

Thanks for your help though! I appreciate it. :neckbeard:
