### ISSUE TITLE
1.2.3 is not a valid semver version

### ISSUE THREAD

**Issue by Hiswe** [stevelacy/gulp-bump#57]
After upgrading from 1.0.0 to 2.x.x and while setting an arbitrary version like this:

```js
bump({
  version: '1.2.3'
})
```

gulp bump always throw an `invalid semver` which wasn't thrown in 1.0.0

Is that related to the fact that opts.type is always set to 'patch' or am I doing something wrong?

**Comment by stevelacy** [comment]
I am not able to reproduce it - I added an example to see if you can run it with correct results:
https://github.com/stevelacy/gulp-bump/commit/6a59b7fdc2c9341aae63f390c0503e87ff5009bc

**Comment by Hiswe** [comment]
@stevelacy thank you very much. 
I'll test it today!

**Comment by Hiswe** [comment]
@stevelacy ok I understand where the problem came from :)
If the key version is not present in the *.json you have the error:

```
events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: Invalid semver
```

so to reproduce :

- remove `"version": "0.1.9",` from examples/package.json
- gulp version
- => error

Prior to version 2.0.0 gulp-bump creates the missing key.
Is that mandatory now?

**Comment by grofit** [comment]
I have the key in there and I get the issue with `2.1.1000`

**Comment by stevelacy** [comment]
@Hiswe Yes, adding support for any file type does mean that I can't assume the file type is always JSON.
Though an error should be thrown when the key does not exist

**Comment by Hiswe** [comment]
@stevelacy Ok thanks :)

I think it should be mentioned on the [readme breaking changes](https://github.com/stevelacy/gulp-bump#breaking-changes)

I let you close the issue if you want so

Thanks again

**Comment by stevelacy** [comment]
Willdo, thanks for finding the issue

**Comment by stevelacy** [comment]
Done - new message now indicates that it could not find the key, or the semver is invalid

2.2.0
