### ISSUE TITLE
Wrong type name when set the specific version

### ISSUE THREAD

**Issue by trikadin** [stevelacy/gulp-bump#59]
![image](https://cloud.githubusercontent.com/assets/1655230/17858845/fde5ae6a-688f-11e6-8c30-acf4d5b51894.png)

**Comment by stevelacy** [comment]
PR?

**Comment by drizzt74** [comment]
Can confirm this, it correctly bumps version to the type set, but the message always reports type: patch
Using latest version (2.6.1)
