### ISSUE TITLE
Doesnt work on config.xml in ionic project

### ISSUE THREAD

**Issue by immnk** [stevelacy/gulp-bump#60]
I have an ionic project which have a config.xml containing version number. The version is not found with bump. Is xml file supported or not?

**Comment by stevelacy** [comment]
What does your version look like?
Please add an example file.

**Comment by immnk** [comment]
This is an example of the file:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<widget id="com.ionicframework.inventory518332" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
  <name>inventory</name>
  <description>
        An Ionic Framework and Cordova project.
    </description>
  <author email="you@example.com" href="http://example.com.com/">
      Your Name Here
    </author>
  <content src="index.html"/>
</widget>

**Comment by stevelacy** [comment]
Just added support for xml files - publishing to version 2.5.0

Let me know how it goes
