### ISSUE TITLE
What if the version in package.json has a prefix like v1.6.1?

### ISSUE THREAD

**Issue by ahmed-abdulmoniem** [stevelacy/gulp-bump#61]
Hi guys,

What if the version in package.json has a prefix like v1.6.1?

When I try the gulp-bump it says that this is invalid semver .. but actually it is so important to support prefixes?

Any workaround?

Thanks.

**Comment by ahmed-abdulmoniem** [comment]
any clue?

**Comment by stevelacy** [comment]
I happen to be the only maintainer of this project and am not madly programming every single weekend, as such "I have a life". Please be respectful as I (or the community) will answer in due time.

I have added support for modifying versions with a prefix, available in published version 2.5.0

**Comment by ahmed-abdulmoniem** [comment]
@stevelacy Respectful!!!!!! What I have said that makes you so angry!
