### ISSUE TITLE
Passing direct version can fail

### ISSUE THREAD

**Issue by dignifiedquire** [stevelacy/gulp-bump#62]
Hey, 

I just ran into this interesting bug. I had a new version `11.1.0` and an old version in `package.json`, of `11.0.1`. When I ran `bump({version: '11.1.0'})`, it ended up with `111.1.0` in the `package.json`

- `gulp-bump@2.5.0`
- `gulp@3.9.1`
- Source: https://github.com/dignifiedquire/aegir/blob/master/tasks/release/bump.js#L19
- Interesting commit history due to the bug: https://github.com/ipfs/js-ipfs-api/commits/master

cc @diasdavid

**Comment by geersch** [comment]
Experiencing the same issue since upgrade from 2.4.0 to 2.5.0.

Setting the version explicitly adds a leading 1 to it.

**Comment by stevelacy** [comment]
Oh deer, sorry about that.

Yep, here it is: https://github.com/stevelacy/bump-regex/commit/7189b70cf52e3f2312d7a53847601f8fb4d457d6

**Comment by stevelacy** [comment]
I found the solution for it, adding more tests and publishing later today when I finish a project with my "real job".

**Comment by dignifiedquire** [comment]
@stevelacy any update on this?

**Comment by stevelacy** [comment]
Haven't gotten around to finishing it yet, the fix I created caused another issue.

**Comment by stevelacy** [comment]
Done, publishing - I added tests for this case, let me know if anything else needs implementing.

**Comment by gravitycode** [comment]
Great work @stevelacy. it works perfectly
