### ISSUE TITLE
Chrome Extension manifest.json

### ISSUE THREAD

**Issue by iamchriswick** [stevelacy/gulp-bump#64]
Is there a way to change prerelease from 0.0.1-2 format to be formated like 0.0.1.2?

Google states that a manifest.json versionnumber must be between 1-4 dot-separated integers each between 0 and 65536.

**Comment by stevelacy** [comment]
Unfortunately not as that would not be valid semver. 
The module https://github.com/npm/node-semver won't even parse it

**Comment by iamchriswick** [comment]
What other options than semver could be looked into then?
