### ISSUE TITLE
Additional xml support

### ISSUE THREAD

**Issue by wtm17** [stevelacy/gulp-bump#65]
We use a pom.xml to generate a war artifact and would appreciate support for bumping a version in an xml file with the following format:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <name>myProject</name>
    <packaging>war</packaging>
    <version>1.0.0</version>
</project>
```

Currently this errors with

```
Message:
    Invalid semver: version key "version" is not found in file
```

**Comment by stevelacy** [comment]
This plugin does support custom regex in `options.regex`
https://github.com/stevelacy/bump-regex/blob/master/index.js#L20

Nevertheless I just added support for versions in xml content.
https://github.com/stevelacy/gulp-bump/releases/tag/2.6.0

**Comment by stevelacy** [comment]
Thanks for reporting, I am not sure why I did not add support for this sooner.

**Comment by wtm17** [comment]
Steve,

Thanks for the quick response. Unfortunately I gave a bad code example. According to the [docs](https://maven.apache.org/guides/introduction/introduction-to-the-pom.html#Minimal_POM), a minimal pom file looks as such

```
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.mycompany.app</groupId>
  <artifactId>my-app</artifactId>
  <version>1</version>
</project>
```

If `modelVersion` is listed above `version` as in the example above, `gulp-bump` is bumping the `modelVersion` property instead of the `version`. This is easily remedied by moving the `version` property above the `modelVersion` property in pom.xml.

**Comment by wtm17** [comment]
An alternative solution is to pass a custom regex in options.regex that is the same as `bump-regex` but that doesn't use the case insensitive flag:

```
{
  type: 'minor',
  regex: new RegExp(
    '([<|\'|\"]?version[>|\'|\"]?[ ]*[:=]?[ ]*[\'|\"]?[a-z]?)(\\d+\\.\\d+\\.\\d+)' +
    '(-[0-9A-Za-z\.-]+)?([\'|\"|<version>]?)')
}
```

**Comment by stevelacy** [comment]
Oh right... Yeah, I had the xml selector choose anything between the `<` and `>` so it could handle `</version>`.
So, this is the test that will break: https://github.com/stevelacy/bump-regex/blob/master/test/index.js#L166
A few options.
- add a case insensitive option
- change it to be case sensitive by default (requires the `opts.key` to be set for `Version`)
The second will be breaking, but would be a new release.

**Comment by wtm17** [comment]
Option 1 would work for us! It could be true by default for backwards compatibility with the option to override.

**Comment by stevelacy** [comment]
Can you test the latest commit to bump-regex on master? 
https://github.com/stevelacy/bump-regex/commit/741b6bb084d40c0d5758b3ec2aba867b91dd831c

**Comment by wtm17** [comment]
Just tested it out and it works as expected.

- When I don't pass `case` option, the behavior works as it did previously
- When I pass a `case: true`, it is bypassing the `modelVersion` node in xml file and updates the `version` node, as expected

**Comment by stevelacy** [comment]
Sounds good, publishing and updating gulp-bump

**Comment by stevelacy** [comment]
Done

**Comment by wtm17** [comment]
Thanks! Working great

![screen shot 2017-01-26 at 11 32 32 am](https://cloud.githubusercontent.com/assets/2049396/22342783/2f920c32-e3bb-11e6-8b09-3cf46add419c.png)
