### ISSUE TITLE
Returns version number twice

### ISSUE THREAD

**Issue by binarykitchen** [stevelacy/gulp-bump#67]
When you have a task like this

```js
gulp.task('bumpVersion', () => {
  const bumpOptions = {}

  if (options.version) {
    bumpOptions.version = options.version
  } else if (options.importance) {
    bumpOptions.type = options.importance
  }

  return gulp.src(['./package.json', './src/ninja-forms-videomail.php'])
    .pipe(plugins.bump(bumpOptions))
    .pipe(plugins.if(options.write, gulp.dest(function (file) {
      return path.dirname(file.path)
    })))
    .on('error', plugins.util.log)
})
```

and use something like this in a bash script

```
read VERSION <<< $(gulp bumpVersion --importance=$IMPORTANCE | awk '/to/ {print $5}')
```

then $VERSION will have the number twice like this `3.3.1 3.3.1` and is invalid.

I think a function inside gulp-bump should return the number only once. Not sure ...

**Comment by stevelacy** [comment]
I am not exactly sure what you are trying to do. Is the version correctly replaced once in the `package.json` and the `./src/ninja-forms-videomail.php`?
All the tests pass with only one version returned.

**Comment by stevelacy** [comment]
if you are just reading the stdout then it is returning the old and the new, the regex should get the new:
![selection_2017071119 29 3601](https://user-images.githubusercontent.com/5648999/28099137-58fa1916-666f-11e7-8577-0e679d6aa3d1.png)

Each file is getting bumped separately, which means that your regex is pulling off a global regex, collecting every single newline with a new `/to/` matcher

**Comment by binarykitchen** [comment]
aahhh, right. i ll have to pipe the output to `awk` and to extract the single number from there then with a regex the proper way ...
