### ISSUE TITLE
Define multiple keys

### ISSUE THREAD

**Issue by binarykitchen** [stevelacy/gulp-bump#70]
Currently `version` is the default key for changing versions. But in WordPress plugins there is also `Stable tag` for versioning inside readme.txt. 

That said, when having package.json and readme.txt both, how can a gulp-bump task bump both in one go? Something like `key: ['version', 'Stable tag']` would be cool.

**Comment by stevelacy** [comment]
Want to send a pr to https://github.com/stevelacy/bump-regex with `keys` as an additional option?
That way there still is the `key` and a new `keys[string]`

**Comment by binarykitchen** [comment]
here u go @stevelacy https://github.com/stevelacy/bump-regex/pull/15

**Comment by stevelacy** [comment]
published 2.8.0
