### ISSUE TITLE
Typescript typings for gulp-bump?

### ISSUE THREAD

**Issue by silkentrance** [stevelacy/gulp-bump#72]
I am trying to set up a typescript based build process where all gulp tasks and assorted other files are implemented using typescript 2.

It would be nice to be able to install the required typings for gulp-bump via ``npm install --save-dev @types/gulp-bump``.

**Comment by silkentrance** [comment]
Alternatively, these could be included as index.d.ts directly in the with the package.

Here is a first stab at a provable version

```
/// <reference types="node"/>

declare function GulpBumpFunction(opts : GulpBump.Options);

declare namespace GulpBump {
  interface Options {
    type? : 'major' | 'minor' | 'patch' | 'prerelease';
    version?: string;
    key?: string;
    keys?: Array<string>;
    case?: boolean;
    preid?: string;
    regex?: Regex;
  }
}

export = GulpBumpFunction
```

**Comment by silkentrance** [comment]
Alternatively, we could also provide the typings for BumpRegex and simply just reference these from the above, e.g.

```
/// <reference types="node"/>
/// <reference types="bump-regex"/>

declare function GulpBump(opts : BumpRegex.Options) : NodeJS.ReadWriteStream;

...
```

**Comment by silkentrance** [comment]
Note: you will still have to 

```
import * as bump from 'gulp-bump';
```

but I can live with that.

**Comment by stevelacy** [comment]
I'd prefer bump-regex to have the typings as this is a gulp plugin

**Comment by silkentrance** [comment]
But gulp-bump also needs typings in order to use typescript for the gulpfile and tasks...

**Comment by silkentrance** [comment]
And here is the working initial stab at the typings with the typings in bump-regex being in place

```
/// <reference types="node"/>
/// <reference types="bump-regex"/>

declare function GulpBump(opts : BumpRegex.Options) : NodeJS.ReadWriteStream;

declare namespace GulpBump {
}

export = GulpBump;
```

**Comment by silkentrance** [comment]
Please note that if you'd also export the plugin as plugin.default, then one could simply use

```
import bump from 'gulp-bump';
```

with a few adjustments to the typings above.

Same goes for bump-regex.

**Comment by stevelacy** [comment]
Exporting as default is a es6+/ts only "feature"

**Comment by silkentrance** [comment]
@stevelacy yeah, you are right.

**Comment by stevelacy** [comment]
I'll keep this open for a bit and see what the community says (:+1: on the first comment to vote), I am hesitant to add a feature for a one-off use case.

**Comment by silkentrance** [comment]
@stevelacy thanks. But it is not so uncommon as parts of the community is beginning to migrate their gulp based build infrastructure over to typescript, see

- https://github.com/Microsoft/TypeScript/blob/master/Gulpfile.ts
- https://www.npmjs.com/package/gulpfile.ts
- https://www.codeproject.com/Tips/1073438/Create-a-gulpfile-and-Write-gulp-Tasks-Using-TypeS

and there is more.

**Comment by silkentrance** [comment]
@stevelacy I am currently working on a PR for DefinitelyTyped based on the PR for bump-regex. Stay tuned.
