### ISSUE TITLE
Using RegEx to bump 'version' in array of PHP config file

### ISSUE THREAD

**Issue by tworonin** [stevelacy/gulp-bump#73]
Hello friends.

This is related to a previous issue (#68) so I didn't know if I should reply there or create a new issue. Apologies if this is incorrect protocol. Any help would be appreciated.

I'm trying to adapt the RegEx method from #68 to bump the version in a config file that uses a PHP array.

`` 'version' => '0.0.1-alpha', ``

I tweaked the regex to compensate (adding a pattern to match '=>'):

```
gulp.task('bump', function(){

   var key = 'version';

   return gulp.src([
      'config/app.php',
   ])
   .pipe(bump({
      type: argv.type,
      regex: new RegExp( "([<|\'|\"]?"+key+"[>|\'|\"]?[ ]*[:=,]?[>]?[ ]*[\'|\"]?[a-z]?)(\\d+\\.\\d+\\.\\d+)(-[0-9A-Za-z\.-]+)?([\'|\"]?)", "i" ),
   }))
   .pipe(gulp.dest(function(file){
      return file.base;
   }));

});
```

but I get the following error:
```
events.js:163                             
      throw er; // Unhandled 'error' event
      ^                                   
Error: Invalid semver -alpha'
```

I am fairly new to RegEx so I may have made a mistake there but I checked it with https://regex101.com/ and it seems to match just fine.

ps) As a test, I created a test PHP file with the exact example from #68:
```
<?php

define( 'MY_PLUGIN_VERSION', '1.2.1' );
```
and gulpfile.js:
```
gulp.task('bump:constant', function(){
   return gulp.src('test-bump.php')
   .pipe(bump({
      regex: new RegExp( "([<|\'|\"]?MY_PLUGIN_VERSION[>|\'|\"]?[ ]*[:=,]?[ ]*[\'|\"]?[a-z]?)(\\d+\\.\\d+\\.\\d+)(-[0-9A-Za-z\.-]+)?([\'|\"|<]?)", "i" ),
   }))
   .pipe(gulp.dest('.'));
});
```
This results in the same error:
```
events.js:163
      throw er; // Unhandled 'error' event
      ^
Error: Invalid semver undefined'
```

Since the base example doesn't work I figure I must have bungled something but I'm at a loss as to where I went wrong.

**I'm on gulp-bump 2.8.0 (Gulp 3.9.1 / npm 5.5.1).**

**Comment by stevelacy** [comment]
I added a test and made a small change to `bump-regex`. Can you test with the latest on master and confirm that it works? https://github.com/stevelacy/bump-regex/commit/c18d591f754ae681b21a192cc12e315e20952187

**Comment by tworonin** [comment]
Nice! Bumped successfully and the custom regex string is no longer needed.
```
return gulp.src([
      'config/app.php',
   ])
   .pipe(bump({
      type: argv.type,
   }))
   .pipe(gulp.dest(function(file){
      return file.base;
   }));
```
Thanks so much for the quick reply and fix!

**Comment by stevelacy** [comment]
I will publish shortly

**Comment by stevelacy** [comment]
2.9.0
