### ISSUE TITLE
Remove prerelease after bump path/major 

### ISSUE THREAD

**Issue by qubiack** [stevelacy/gulp-bump#75]
We have a problem with gulp bump. When we use use:

`
    var type = 'prerelease';
    gulp.src('./package.json')
       .pipe(bump({
           key: "version",
           type: type
       }))
       .pipe(gulp.dest('./'));
`
we get 0.0.1-0, but how we can remove prerelease from version? When we use type=path we get: 0.0.2-0.

**Comment by stevelacy** [comment]
https://github.com/stevelacy/bump-regex/blob/master/test/index.js#L151
