### ISSUE TITLE
Preserve path when writing files

### ISSUE THREAD

**Issue by stefanobartoletti** [stevelacy/gulp-bump#84]
Given the following example

```javascript
gulp.task('version', function(){
  gulp.src(['./config/setup.json', './style.css', './package.json'])
  .pipe(bump({type:'major'}))
  .pipe(gulp.dest('./'));
});
```
when outputting files, right now `gulp.bump` writes them all in the project root (`./`) without taking into account the relative paths of every single file. So, in example, `./config/setup.json` is being copied into a new file, `./setup.json`, instead of simply updating the source inside `./config/`.

I think that a more intuitive and desirable behavior would be to preserve the file paths and simply overwrite the source files when `gulp.dest` is set to `./`.

**Comment by stevelacy** [comment]
Your task is written to only have one output folder. gulp-bump does not handle any paths or writes in any way.

https://gulpjs.com/docs/en/getting-started/working-with-files

**Comment by stefano-b** [comment]
Thank you, I checked and solved by adding `{ base: './' }` to `gulp.src`.
